optimizer: 'SGD'
dataset: 'cifar_biased_ul5'
num_sample: 1
weight_decay: 0.0005
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
lr_sch: OneCycle
experiment: 
  name: 'full_bandit_feedback_SupKL_c2'
  n_exp: 1
  feedback: 'bandit'
  regularizers:
    KL: 0.001
    SupKL: 0.01
    eps: 1.0
  labeled_portion: u5
