optimizer: 'SGD'
dataset: 'cifar_f_ul1_1.0_tau0.2'
num_sample: 1
weight_decay: 
- 0.001
- 0.01
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0
experiment: 
  name: 'full_ips_bandit_feedback'
  n_exp: 3
  n_trials: 5
  feedback: 'bandit'
  regularizers: null
  labeled_portion: u1
