template: true
optimizer: 'SGD'
dataset: 'cifar_raw_linear/${TAU}_${UL}'
num_sample: 1
weight_decay: 
- 0.0001
- 0.05
lr: 0.001
epochs: 60
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0
experiment: 
  name: 'full_ips_bandit_feedback_KL2K'
  n_exp: 3
  n_trials: 1
  feedback: 'bandit'
  regularizers:
    KL2: 
    - 0.05
    - 5.0
