optimizer: 'SGD'
dataset: 'cifar_ul4_1.0_tau0.1'
num_sample: 1
weight_decay: 
- 0.002
- 0.05
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  name: 'full_bandit_feedback_KL'
  n_exp: 3
  n_trials: 5
  feedback: 'bandit'
  regularizers:
    KL:
    - 0.05
    - 5.0
  labeled_portion: u4
