optimizer: 'SGD'
<<<<<<< HEAD:code/config/cifar/tau1/ul49/KL.yaml
dataset: 'cifar_ul49_1.0'
=======
dataset: 'cifar_ul49_1.0_tau0.1'
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043:code/config/cifar/tau10/ul49/KL.yaml
num_sample: 1
weight_decay: 
- 0.0001
- 0.0001
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  name: 'KL_best'
  n_exp: 3
  n_trials: 1
  feedback: null
  regularizers:
    KL:
    - 1.0
    - 1.0
  labeled_portion: u49
