optimizer: 'SGD'
dataset: 'cifar_pretrained_feature/base'
num_sample: 1
weight_decay: 0.0001
lr_sch: CosineAnnealingLR
lr: 0.01
epochs: 200
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  name: 'supervised'
  n_exp: 1
  n_trials: 1
  feedback: 'supervised'
  regularizers: null
  labeled_portion: u0
