optimizer: 'SGD'
dataset: 'cifar'
num_sample: 1
weight_decay: 0.00005
lr: 0.015
epochs: 100
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  feedback: 'semi_bandit'
  n_exp: 10
  regularizers: null
  labeled_portion: 0.2