optimizer: 'SGD'
dataset: 'letter/base'
num_sample: 1
weight_decay: 0.00000
lr: 5.0
lr_sch: CosineAnnealingLR
epochs: 50
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  name: 'supervised'
  n_exp: 1
  n_trials: 1
  feedback: 'supervised'
  regularizers: null
  labeled_portion: u0
