template: true
optimizer: 'SGD'
dataset: 'yeast_raw_linear/${TAU}_${UL}'
num_sample: 1
lr: 0.1
lr_sch: CosineAnnealingLR
epochs: 500
batch_size: 2000
batch_log_interval: 50
train_limit: 500_000
lse_lamda: 2.0
lamda: 0
experiment:
  name: 'full_lse_bandit_feedback_AR'
  n_exp: 8
  n_trials: 6
  feedback: 'bandit'
  regularizers:
    AlphaRenyi:
      type: 1
      beta: [0.001, 10]