template: true
optimizer: 'SGD'
dataset: 'yeast_raw_linear/${TAU}_${UL}'
num_sample: 1
lr: 0.1
lr_sch: CosineAnnealingLR
epochs: 500
batch_size: 2000
batch_log_interval: 50
train_limit: 500_000
power_mean_lamda: 0.1
lamda: 0
experiment: 
  name: 'full_powermean_bandit_feedback'
  n_exp: 8
  n_trials: 1
  feedback: 'bandit'
  regularizers: null