template: true
optimizer: 'SGD'
dataset: 'letter_raw_linear/${TAU}_${UL}'
num_sample: 1
lr: 0.1
lr_sch: CosineAnnealingLR
epochs: 300
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0
experiment:
  name: 'full_ips_bandit_feedback_KL'
  n_exp: 3
  n_trials: 3
  feedback: 'bandit'
  regularizers:
    KL: 
    - 0.05
    - 5.0