optimizer: 'SGD'
dataset: 'cifar_ul9_1.0_tau0.2'
num_sample: 5
weight_decay: 
- 0.002
- 0.002
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  name: 'full_bandit_feedback_KL_ns5'
  n_exp: 3
  n_trials: 1
  feedback: 'bandit'
  regularizers:
    KL: 
    - 2.0
    - 2.0
  labeled_portion: u9
