template: true
optimizer: 'SGD'
dataset: 'opd'
num_sample: 0.6w
lr: 0.01
epochs: 300
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lse_lamda: 0.1
lamda: 0
experiment:
  name: 'full_lse_bandit_feedback_AR'
  n_exp: 3
  n_trials: 3
  feedback: 'bandit'
  regularizers:
    AlphaRenyi:
      type: 1
      beta: [0.001, 10]