optimizer: 'SGD+Adam'
dataset: 'cifar_0.4_0.01'
num_sample: 1
weight_decay: 0.0005
lr: 0.005
max_lr: 0.01
epochs: 200
batch_size: 256
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  name: 'bandit_fGAN_RKL_c3'
  n_exp: 1
  feedback: 'bandit'
  regularizers: 
    KL: 0.05
  labeled_portion: 1.0
GAN:
  V_update: 1
  V_step: 3
  divergence: RKL