optimizer: 'SGD'
dataset: 'glass/base'
num_sample: 1
weight_decay: 0.00001
lr: 1.0
epochs: 100
lr_sch: CosineAnnealingLR
batch_size: 16
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  name: 'supervised'
  n_exp: 1
  n_trials: 1
  feedback: 'supervised'
  regularizers: null
  labeled_portion: u0
