optimizer: 'SGD'
dataset: 'cifar_ul9_1.0_tau0.1'
num_sample: 1
weight_decay: 
- 0.0001
- 0.0001
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
<<<<<<< HEAD:code/config/cifar/tau5/ul9/KL2.yaml
  name: 'KL2_best'
=======
  name: 'KL_best'
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043:code/config/cifar/tau10/ul9/KL.yaml
  n_exp: 3
  n_trials: 1
  feedback: null
  regularizers:
<<<<<<< HEAD:code/config/cifar/tau5/ul9/KL2.yaml
    KL2:
=======
    KL:
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043:code/config/cifar/tau10/ul9/KL.yaml
    - 1.0
    - 1.0
  labeled_portion: u9
